#!/bin/bash

find ./ -iname \*.go -print | sed '/pb.go/d' | xargs grep -n --color -H $1 ;
find ./ -iname \*.proto -exec grep -n --color  -H $1 \{\} \;
find ./ -iname \*.ts -exec grep -n --color  -H $1 \{\} \;
find ./ -iname \*.json -exec grep -n --color  -H $1 \{\} \;
find ./ -iname \*.sh -exec grep -n --color  -H $1 \{\} \;
find ./ -iname \*.py -exec grep -n --color  -H $1 \{\} \;
